#!/bin/sh

. ~/scripts/wofi/config

entry=$(printf "poweroff\nreboot\nexit\nlock\nsuspend" | wofi_dmenu "power")

if [ $entry = "poweroff" ] || [ $entry = "reboot" ]; then
    if [ $(~/scripts/wofi/confirm "confirm") = "yes" ]; then
        doas $entry
    fi
elif [ $entry = "lock" ]; then
    swaylock
elif [ $entry = "suspend" ]; then
    doas zzz
elif [ $entry = "exit" ]; then
    if [ $(~/scripts/wofi/confirm "exit?") = "yes" ]; then
        doas killall swhkd swhks
        wayland-logout
    fi
fi
