#!/bin/sh

. /etc/environment

rofi_dmenu() {
    rofi -dmenu -i -no-custom -window-title $1 -sep $2
}

rofi_allow_cus() {
    rofi -dmenu -i -window-title $1 -sep $2
}

wofi_dmenu() {
    wofi --term "kitty" -i --prompt $1 -G --dmenu
}
