#!/bin/sh

. ~/scripts/rofi/config

entry=$(ls ~/.local/share/nvim/session/ | rofi_dmenu "vim" ' ')

if [ $entry != '' ]; then
    kitty --class=nvim,nvim --name nvim --hold -e fish -c "lvim -S ~/.local/share/nvim/session/$entry"
fi
