#!/bin/sh

exec nitrogen --restore &

xrdb ~/.Xresources &

export PATH="$HOME/.cargo/bin:/usr/local/bin:$HOME/.local/bin:$PATH"
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export GDK_SCALE=1
export GDK_DPI_SCALE=1
export GTK_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export QT_IM_MODULE=fcitx
SDL_IM_MODULE=fcitx

exec xinput set-prop "SYNA1D31:00 06CB:CD48 Touchpad" "Synaptics Tap Action" 0, 0, 0, 0, 1, 3, 2 &

killall swhks
doas killall swhkd
sleep 1
swhks &
pkexec /usr/bin/swhkd -c $1 &

# picom &

redshift -PO 3600 &

clash &

jgmenu --hide-on-startup &

musikcubed &

nm-applet &

sleep 1

setxkbmap -option caps:escape &

fcitx5 -d -r &

eww daemon &

dunst &

/usr/libexec/polkit-gnome-authentication-agent-1 &
