#!/bin/sh

exec nitrogen --restore &

xrdb ~/.Xresources &

export QT_AUTO_SCREEN_SCALE_FACTOR=1
export GDK_SCALE=1
export GDK_DPI_SCALE=1
export GTK_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export QT_IM_MODULE=fcitx
SDL_IM_MODULE=fcitx

exec xinput set-prop "SYNA1D31:00 06CB:CD48 Touchpad" "Synaptics Tap Action" 0, 0, 0, 0, 1, 3, 2 &

doas rm -rf /run/user/0/swhk*
killall swhks
doas killall swhkd
XDG_RUNTIME_DIR=/run/user/0 swhks &
doas pkexec swhkd -c $1 &

picom &

redshift -PO 3600 &

clash &

jgmenu --hide-on-startup &

musikcubed &

kdeconnect-indicator &

nm-applet &

sleep 1

setxkbmap -option caps:escape &

fcitx5 -d -r &

eww daemon &
