#!/bin/sh

msgTag=volume
volume="$(pamixer --get-volume)"
mute="$(pamixer --get-mute)"
if [ $volume = "0" ] || [ $mute = "true" ]; then
    # Show the sound muted notification
    dunstify -a "changeVolume" -u normal -i audio-volume-muted -h string:x-dunst-stack-tag:$msgTag "Volume muted" 
else
    # Show the volume notification
    dunstify -a "changeVolume" -u normal -i audio-volume-high -h string:x-dunst-stack-tag:$msgTag \
    -h int:value:"$volume" "Volume: ${volume}%"
fi
