#!/bin/sh

if grep -q "shadow = true" ~/.config/picom.conf; then
    sd "shadow = true" "shadow = false" ~/.config/picom.conf
else
    sd "shadow = false" "shadow = true" ~/.config/picom.conf
fi

killall picom

sleep 0.1

picom &
